cc_library(
    name = "egl_streams",
    deps = [
        "@cuda//:cuda",
        "@egl//:egl",
    ],
    srcs = [
        "egl_common.cpp"
    ],
    hdrs = [
        "egl_common.h"
    ],
    visibility = ["//visibility:public"]
)